# Generated by Django 5.2.7 on 2025-10-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_bookrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='ReadingHistory',
        ),
        migrations.DeleteModel(
            name='ReadingGoal',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
