version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: online_library_postgres
    environment:
      POSTGRES_DB: online_library
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backups:/backups  # Папка для бэкапов
    restart: unless-stopped
    networks:
      - library_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: online_library_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - library_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  library_network:
    driver: bridge
